### ISSUE TITLE
Debian Buster missing KiCad

### ISSUE THREAD

**Issue by luisjperez** [KiCad/kicad-website#285]
I was looking in the Debian [Buster] package repositories for KiCad without success.
Do you know any reason it is not present in Debian Buster?

**Comment by marekr** [comment]
Sorry, but nobody on kicad development maintains any linux distro specific packages. It is entirely up to the debian maintainer(s) to build and package kicad for Debian. There is nothing we can do. 

If anything, I believe its because the Debian maintainer(s) are never happy with how its packaged.

But, the best place to ask is on the Debian mailing lists.

**Comment by marekr** [comment]
@tijuca Sorry, bad wording on my part. I meant to say that packaging was a separate volunteer effort rather than official focus ;)

Meh, package issues are always awkward to answer...not quite website...but not quite kicad-dev either :/

**Comment by tijuca** [comment]
No worries, I got it. And I know also that mostly the problem is that people/users don't know how some things internally in Debian work and it's all based on a voluntary base. Like KiCad ...
