### ISSUE TITLE
Title case and/or wording of tag line

### ISSUE THREAD

**Issue by cpavlina** [KiCad/kicad-website#31]
The tag line it at least mildly incorrect:

> A Cross Platform And Open Source Electronics Design Automation Suite

At very least, "And" should be "and" by convention. I was going to just submit a PR, but really, I'm not fond of how long this is in general, it feels awkward to me. So I thought I'd ask. What about this?

> Cross Platform and Open Source Electronics Design

Or

> Cross Platform, Open Source Electronics Design

We could even omit "Cross Platform" - most large open source projects these days are.

To me, it seems awkward how the tagline flows into the next line - particularly breaking in the middle of an "important" phrase, I don't like "Electronics \\ Design Automation" being split like that:

http://misc.c4757p.com/tagline.png

Thoughts?

**Comment by nickoe** [comment]
The rason for the A in and being a capital letter is that hugo makes it so. The description is defined in the config.toml and used as `.Site.Params.Description` in the template. I have not investigated what exactly makes hugo make this conversion.

The reason for the cross platform, was because I had someone give me the feedback that it was not obvious that it was working on multiple platforms, so I tried to emphasize this by explicitly write "cross platform". The thought of writing out the Electronics Design Automation (EDA) is because it says KiCad EDA on the page. I consider more the tagline as you call it a short description, rather than a tagline or catch phrase as I think your think it should be.

I think it would still be good to include the cross platform in the tagline. It will make people describing KiCad to other people use this term too. I think this is in general good, to keep people aware that there is other systems that the one you use... -- in general.

_Cross Platform, Open Source Electronics Design_ could be a good candidate if you want to simplify it a bit.

**Comment by Caerbannog** [comment]
At least drop the "A" and move the text from `.Site.Params.Description` to the HTML to have lower case "and".
I like @nickoe's version, I had to google EDA the first time I read KiCad's website. Not a native speaker.

**Comment by marekr** [comment]
Or just remove the title macro that puts it in title case......

**Comment by TheNikomo** [comment]
How's this?
![KiCad frontpage title proposal](https://i.imgur.com/Jp9HLBn.png)
People seriously don't need the entire acronym spelled out for them - veterans don't care, newbies connect 2/3 of the dots, and can Google the last one if they really want to know, but knowing it's a suite of tools that allows you to design electronics, is good enough for those users.

**Comment by nickoe** [comment]
Would it make sense to stuff in the word free? So many options to talk about here for such a small string :yum:

**Comment by TheNikomo** [comment]
If you wanted to go from OSS to FOSS, you'd have to stuff in "Free And", which might be a bit much, but "Free Software" instead of "Open Source" could work.

**Comment by Caerbannog** [comment]
Another proposal:
![motto](https://cloud.githubusercontent.com/assets/242172/9706715/b76e8430-54ee-11e5-9748-8f3932ed98ff.png)

**Comment by marekr** [comment]
1 Month later...we should probably settle this

@nickoe

**Comment by reportingsjr** [comment]
This is an old topic, but I much prefer @TheNikomo version of the tag line.

"A cross platform, open source, electronics design suite"

**Comment by nickoe** [comment]
I think I will close this issue since it has been open for long with merely bikeshedding (not meant in a negative way here), and the case has been fixed as originally suggested. I like the current:

> A Cross Platform and Open Source Electronics Design Automation Suite
